// <auto-generated />
using System;
using ConsumoDeLamina.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ConsumoDeLamina.Data.Migrations
{
    [DbContext(typeof(ApplicationDataContext))]
    partial class ApplicationDataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("ConsumoDeLamina.Entities.Models.ConsumoDeLamin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<DateTime>("FechaFinal")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaInicial")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdProyecto")
                        .HasColumnType("int");

                    b.Property<string>("Notas")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ConsumoDeLamina");
                });

            modelBuilder.Entity("ConsumoDeLamina.Entities.Models.ConsumoDeLaminaDetalles", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<double>("Cantidad10")
                        .HasColumnType("float");

                    b.Property<double>("Cantidad14")
                        .HasColumnType("float");

                    b.Property<double>("Cantidad16")
                        .HasColumnType("float");

                    b.Property<double>("Cantidad18")
                        .HasColumnType("float");

                    b.Property<double>("Cantidad20")
                        .HasColumnType("float");

                    b.Property<double>("Cantidad22")
                        .HasColumnType("float");

                    b.Property<double>("Cantidad24")
                        .HasColumnType("float");

                    b.Property<double>("Cantidad26")
                        .HasColumnType("float");

                    b.Property<double>("Peso10")
                        .HasColumnType("float");

                    b.Property<double>("Peso14")
                        .HasColumnType("float");

                    b.Property<double>("Peso16")
                        .HasColumnType("float");

                    b.Property<double>("Peso18")
                        .HasColumnType("float");

                    b.Property<double>("Peso20")
                        .HasColumnType("float");

                    b.Property<double>("Peso22")
                        .HasColumnType("float");

                    b.Property<double>("Peso24")
                        .HasColumnType("float");

                    b.Property<double>("Peso26")
                        .HasColumnType("float");

                    b.Property<double>("PesoLiso18")
                        .HasColumnType("float");

                    b.Property<double>("PesoLiso20")
                        .HasColumnType("float");

                    b.Property<double>("PesoLiso22")
                        .HasColumnType("float");

                    b.Property<double>("PesoLiso24")
                        .HasColumnType("float");

                    b.Property<double>("PesoLiso26")
                        .HasColumnType("float");

                    b.Property<double>("PesoLiso28")
                        .HasColumnType("float");

                    b.Property<double>("PesoSR26")
                        .HasColumnType("float");

                    b.Property<double>("PesoSR28")
                        .HasColumnType("float");

                    b.Property<int?>("consumoDeLaminaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("consumoDeLaminaId");

                    b.ToTable("ConsumoDeLaminaDetalles");
                });

            modelBuilder.Entity("ConsumoDeLamina.Entities.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("PasswordHash")
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("PasswordSalt")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ConsumoDeLamina.Entities.Models.ConsumoDeLaminaDetalles", b =>
                {
                    b.HasOne("ConsumoDeLamina.Entities.Models.ConsumoDeLamin", "consumoDeLamina")
                        .WithMany("ConsumoDeLaminaDetalles")
                        .HasForeignKey("consumoDeLaminaId");

                    b.Navigation("consumoDeLamina");
                });

            modelBuilder.Entity("ConsumoDeLamina.Entities.Models.ConsumoDeLamin", b =>
                {
                    b.Navigation("ConsumoDeLaminaDetalles");
                });
#pragma warning restore 612, 618
        }
    }
}
